# Generated by Django 4.1.3 on 2022-11-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("age", models.IntegerField()),
                ("password", models.CharField(default="", max_length=50)),
                ("class_school", models.IntegerField()),
                ("section", models.IntegerField()),
                ("school_name", models.CharField(default="", max_length=50)),
                ("father_name", models.CharField(default="", max_length=50)),
                ("cnic", models.CharField(default="", max_length=50)),
                ("photo", models.ImageField(default="", upload_to="myimage")),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
